name: Pull Request Creation for dependencies
on:  
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'

jobs:
  call-workflow-dependencies:
    uses: ./.github/workflows/pr-creation.yml
